const dogs = [
  {
    name: "Rex",
    avatar: "/images/dog-rex.jpg",
    age: 25,
    bio: "Art. Literature. Natural wine. Yoga.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Bella",
    avatar: "/images/dog-bella.jpg",
    age: 36,
    bio: "Yup, that's my owner. U can meet him if you want",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Teddy",
    avatar: "/images/dog-teddy.jpg",
    age: 43,
    bio: "Chasing squirrels is my jam. Want to join?",
    hasBeenSwiped: false,
    hasBeenLiked: false,
    attribute: "",
  },
  {
    name: "Miri",
    avatar: "/images/golden.jpg",
    age: 24,
    bio: "Chasing squirrels is my jam. Want to join?",
    hasBeenSwiped: false,
    hasBeenLiked: false,
    attribute:
      "https://unsplash.com/@richardbrutyo?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash",
  },
  {
    name: "Dodi",
    avatar: "/images/doodle.jpg",
    age: 21,
    bio: "Beach lover and sun-soaker. Let's go!",
    hasBeenSwiped: false,
    hasBeenLiked: false,
    attribute:
      "https://unsplash.com/@richardbrutyo?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash",
  },
  {
    name: "Daisy",
    avatar: "/images/dachshund.jpg",
    age: 31,
    bio: "Beach lover and sun-soaker. Let's go!",
    hasBeenSwiped: false,
    hasBeenLiked: false,
    attribute:
      "https://unsplash.com/@erdaest?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash",
  },
  {
    name: "Rudi",
    avatar: "/images/dog-basenji.jpg",
    age: 30,
    bio: "Always up for an adventure. Swipe right!",
    hasBeenSwiped: false,
    hasBeenLiked: false,
    attribute: "Image by bublikhaus on Freepik",
  },
  {
    name: "Reddy",
    avatar: "/images/dog-collie.jpg",
    age: 38,
    bio: "Active and playful. Let's have fun together!",
    hasBeenSwiped: false,
    hasBeenLiked: false,
    attribute: "Image by master1305 on Freepik",
  },
  {
    name: "Pumi",
    avatar: "/images/dog-bernard.jpg",
    age: 29,
    bio: "Seeking a cuddle buddy and treat lover.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
    attribute: "",
  },
  {
    name: "Jani",
    avatar: "/images/jamie.jpg",
    age: 23,
    bio: "Playdates and wagging tails, here I come.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
    attribute: "Photo by Jamie Street on Unsplash",
  },
];

export { dogs };
