const dogs = [
  {
    name: "Rex",
    avatar: "/images/dog-rex.jpg",
    age: 25,
    bio: "Art. Literature. Natural wine. Yoga.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Bella",
    avatar: "/images/dog-bella.jpg",
    age: 43,
    bio: "Yup, that's my owner.<br> U can meet him if you want",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Teddy",
    avatar: "/images/dog-teddy.jpg",
    age: 30,
    bio: "How you doin?",
    hasBeenSwiped: false,
    hasBeenLiked: false,
    attribute: "",
  },
  {
    name: "Rudi",
    avatar: "/images/dog-basenji.jpg",
    age: 30,
    bio: "How you doin?",
    hasBeenSwiped: false,
    hasBeenLiked: false,
    attribute: "Image by bublikhaus on Freepik",
  },
  {
    name: "Reddy",
    avatar: "/images/dog-collie.jpg",
    age: 30,
    bio: "How you doin?",
    hasBeenSwiped: false,
    hasBeenLiked: false,
    attribute: "Image by master1305 on Freepik",
  },
  {
    name: "Pumi",
    avatar: "/images/dog-bernard.jpg",
    age: 30,
    bio: "How you doin?",
    hasBeenSwiped: false,
    hasBeenLiked: false,
    attribute: "Image by wirestock on Freepik",
  },
];

export { dogs };
